import { ImapFlow } from 'imapflow';
import { logger } from '../logger.js';
import { getImapConfig } from './smtpGateway.js';
import type { WireProvider } from '../creds/mailboxStore.js';

const DEBUG_REPLY_DETECT = String(process.env.DEBUG_REPLY_DETECT ?? '').trim() === '1';

/**
 * Canonicalize Message-IDs so we can match regardless of angle brackets.
 *
 * Canonical format used internally: no surrounding angle brackets.
 * Example:
 *   - "<4117c0...@domain>" -> "4117c0...@domain"
 *   - "4117c0...@domain"  -> "4117c0...@domain"
 */
export function normalizeMessageId(raw: unknown): string {
  const v = String(raw ?? '').trim();
  if (!v) return '';
  return v.replace(/[<>]/g, '').trim();
}

/**
 * Format a Message-ID for use in RFC 5322 headers (angle brackets required).
 */
export function formatMessageIdForHeader(raw: unknown): string | undefined {
  const id = normalizeMessageId(raw);
  if (!id) return undefined;
  return `<${id}>`;
}

function debugLog(msg: string, extra?: Record<string, unknown>): void {
  if (!DEBUG_REPLY_DETECT) return;
  logger.debug(extra ?? {}, msg);
}

/**
 * Senders that produce delivery-status notifications rather than human replies.
 *
 * A bounce must never be scored as a reply. The header searches below
 * deliberately drop the sender filter ("if it references our Message-ID it is
 * relevant to this thread"), and an Exchange NDR is generated by our own
 * tenant, quotes the original message, and can carry its In-Reply-To — so it is
 * exactly the shape those searches are looking for. If one matched, the
 * sequence would be cancelled as "replied" and the campaign's reply metrics
 * would count the worst addresses on the list as its best responses.
 *
 * Whether a given NDR actually carries In-Reply-To on itself varies by
 * provider, and this guard deliberately does not depend on the answer: it
 * excludes DSN senders outright, which is correct either way.
 *
 * MicrosoftExchange<32 hex>@domain is the standard Exchange Online NDR sender.
 */
const DSN_SENDER_RE =
  /^(mailer-daemon|postmaster|no-?reply|microsoftexchange[0-9a-f]{16,}|.*\.?bounces?)@/i;

export function isDeliveryStatusSender(address: unknown): boolean {
  const a = String(address ?? '').trim().toLowerCase();
  if (!a) return false;
  return DSN_SENDER_RE.test(a);
}

/**
 * True when a candidate message cannot be a genuine human reply.
 *
 * Checks the sender, and the RFC 3464 report content type that every
 * conforming DSN carries regardless of who it claims to be from.
 */
export function isNotAHumanReply(envelopeFrom: unknown, contentType?: unknown): boolean {
  if (isDeliveryStatusSender(envelopeFrom)) return true;
  const ct = String(contentType ?? '').toLowerCase();
  return ct.includes('multipart/report') || ct.includes('message/delivery-status');
}

/**
 * Flatten an IMAP BODYSTRUCTURE tree into a space-joined string of its MIME
 * types, for isNotAHumanReply's content-type check.
 *
 * A DSN is `multipart/report; report-type=delivery-status` at the top with a
 * `message/delivery-status` part beneath it, so the marker can sit at either
 * level depending on the generating server — walking the whole tree avoids
 * having to care which.
 *
 * This exists because the content-type half of isNotAHumanReply was dead code:
 * both fetch sites requested only `{ envelope, internalDate }` and passed one
 * argument, so `contentType` was always undefined and the sender regex was the
 * only guard actually running. The unit test for isNotAHumanReply passed the
 * whole time — it called the function directly, which proved the rule worked
 * without proving anything ever applied it.
 */
export function collectContentTypes(node: unknown): string {
  const types: string[] = [];
  // Depth-capped: BODYSTRUCTURE is attacker-influenced input (the message is
  // whatever a stranger sent us), and a deeply nested multipart should cost a
  // truncated string rather than a blown stack.
  const walk = (n: any, depth: number): void => {
    if (!n || typeof n !== 'object' || depth > 10) return;
    if (typeof n.type === 'string') types.push(n.type.toLowerCase());
    if (Array.isArray(n.childNodes)) {
      for (const child of n.childNodes) walk(child, depth + 1);
    }
  };
  walk(node, 0);
  return types.join(' ');
}

/**
 * Filter IMAP search hits down to messages that are genuinely human replies
 * arriving AFTER the initial send.
 *
 * Two problems handled in one fetch, because both need the envelope anyway:
 *
 * 1. BOUNCES. See isNotAHumanReply — a DSN must never gate a follow-up.
 *
 * 2. IMAP `SINCE` IS DATE-GRANULAR. It filters on INTERNALDATE to a whole day,
 *    so "since 2026-07-27T16:00" is really "since 2026-07-27T00:00" and an
 *    unrelated email that arrived that morning — before we ever sent — counts
 *    as a reply and silently cancels the sequence. The protocol offers nothing
 *    finer, so the fix is to over-fetch and compare the real timestamp here.
 */
async function hasGenuineReply(
  client: ImapFlow,
  hits: unknown,
  since: Date,
  hasValidSince: boolean,
): Promise<boolean> {
  if (!Array.isArray(hits) || hits.length === 0) return false;

  // Cap the fetch: a thread with hundreds of hits is pathological, and the
  // newest are the ones that could be a reply.
  const sample = hits.slice(-25);
  for await (const msg of client.fetch(sample as any, {
    envelope: true,
    internalDate: true,
    // Required for the content-type half of isNotAHumanReply — without it that
    // check silently no-ops and only the sender regex protects this path.
    bodyStructure: true,
  })) {
    const envelope = (msg as any)?.envelope;
    const from = envelope?.from?.[0]?.address;
    const contentTypes = collectContentTypes((msg as any)?.bodyStructure);

    if (isNotAHumanReply(from, contentTypes)) {
      debugLog('Reply check: ignoring delivery-status notification', { from, contentTypes });
      continue;
    }

    if (hasValidSince) {
      const received = (msg as any)?.internalDate ?? envelope?.date;
      // Only reject on a timestamp we could actually read — a missing
      // internalDate must not silently discard a real reply.
      if (received && new Date(received).getTime() < since.getTime()) {
        debugLog('Reply check: ignoring message predating the initial send', { received });
        continue;
      }
    }

    return true;
  }
  return false;
}

/**
 * Reply detection used by the follow-up scheduler.
 *
 * We check the sender mailbox INBOX for messages:
 * - From: recipientEmail
 * - Sent/received since initialSentAt
 * - Optionally referencing the original Message-ID (In-Reply-To / References)
 */
export async function hasRecipientReplied(input: {
  userId: string;
  provider: WireProvider;
  recipientEmail: string;
  initialSentAt: string;
  originalMessageId?: string;
}): Promise<boolean> {
  const recipientEmail = String(input.recipientEmail ?? '').trim().toLowerCase();
  if (!recipientEmail) return false;

  const sinceDate = new Date(input.initialSentAt);
  const hasValidSince = !Number.isNaN(sinceDate.getTime());

  let imap: Awaited<ReturnType<typeof getImapConfig>>;
  try {
    // Sender mailbox credentials resolved from the DB for this tenant.
    imap = await getImapConfig(input.userId, input.provider);
  } catch (err: any) {
    debugLog('Reply check: failed to resolve mailbox credentials', {
      provider: input.provider,
      err: err?.message ?? String(err),
    });
    return false;
  }

  const client = new ImapFlow({
    host: imap.host,
    port: imap.port ?? 993,
    secure: imap.secure ?? true,
    auth: imap.auth,
    logger: false,
    tls: {
      rejectUnauthorized: true,
      minVersion: 'TLSv1.2',
    },
    connectionTimeout: input.provider === 'microsoft' ? 60000 : 15000,
    greetingTimeout: input.provider === 'microsoft' ? 60000 : 15000,
    socketTimeout: input.provider === 'microsoft' ? 120000 : 15000,
  } as any);

  try {
    await client.connect();

    // Search INBOX for replies
    await client.mailboxOpen('INBOX', { readOnly: true });

    // Criteria enforcing the sender (used for fallback / subject match)
    const baseCriteriaSender: any = {
      from: recipientEmail,
    };

    // Criteria IGNORING the sender (used for precise Message-ID match)
    // We trust that if an email references our Message-ID, it is relevant to this thread
    // regardless of which alias/colleague sent it.
    const baseCriteriaId: any = {};

    if (hasValidSince) {
      // `since` uses INTERNALDATE which is good enough for gating followups.
      baseCriteriaSender.since = sinceDate;
      baseCriteriaId.since = sinceDate;
    }

    const originalMessageId = normalizeMessageId(input.originalMessageId);

    debugLog('Reply check: starting IMAP search', {
      provider: input.provider,
      hasValidSince,
      since: hasValidSince ? sinceDate.toISOString() : undefined,
      hasOriginalMessageId: Boolean(originalMessageId),
    });

    // If we don't have a Message-ID, fall back to "any inbound message from
    // recipient since initialSentAt". Routed through the same filter: `since`
    // is only accurate to the day, so a mail this contact sent us at 09:00 —
    // hours before our campaign went out at 16:00 — would otherwise read as a
    // reply to a message they had not yet received.
    if (!originalMessageId) {
      const r = await client.search(baseCriteriaSender);
      return await hasGenuineReply(client, r, sinceDate, hasValidSince);
    }

    // IMAP SEARCH HEADER matches substring in header value.
    // Searching for the canonical (unbracketed) ID matches both:
    //   - In-Reply-To: <id@domain>
    //   - In-Reply-To: id@domain
    const criteriaInReplyTo = {
      ...baseCriteriaId,
      header: {
        'in-reply-to': originalMessageId,
      },
    };

    const criteriaReferences = {
      ...baseCriteriaId,
      header: {
        references: originalMessageId,
      },
    };

    const r1 = await client.search(criteriaInReplyTo);
    if (await hasGenuineReply(client, r1, sinceDate, hasValidSince)) {
      debugLog('Reply check: matched In-Reply-To');
      return true;
    }

    const r2 = await client.search(criteriaReferences);
    if (await hasGenuineReply(client, r2, sinceDate, hasValidSince)) {
      debugLog('Reply check: matched References');
      return true;
    }

    // Optional last-resort fallback: any inbound email from recipient whose subject looks like a reply.
    // This helps when clients omit References/In-Reply-To but still use a Re: subject.
    const r3 = await client.search(baseCriteriaSender);
    if (Array.isArray(r3) && r3.length > 0) {
      const sample = r3.slice(-10);
      for await (const msg of client.fetch(sample, {
        envelope: true,
        internalDate: true,
        bodyStructure: true,
      })) {
        const envelope = (msg as any)?.envelope;
        const subj = String(envelope?.subject ?? '').trim();

        // An NDR's subject is "Undeliverable: RE: <original subject>", which
        // does NOT start with "Re:" — but a forwarded or localized variant can,
        // and the same guard is applied on every path so no single one has to
        // be the clever exception.
        if (isNotAHumanReply(envelope?.from?.[0]?.address, collectContentTypes((msg as any)?.bodyStructure))) continue;

        // Same day-granularity correction as hasGenuineReply.
        const received = (msg as any)?.internalDate ?? envelope?.date;
        if (hasValidSince && received && new Date(received).getTime() < sinceDate.getTime()) continue;

        if (/^re\s*:/i.test(subj)) {
          debugLog('Reply check: matched fallback subject', { subject: subj });
          return true;
        }
      }
    }

    return false;
  } catch (err) {
    logger.error({ err }, 'Error checking replies');
    return false;
  } finally {
    try {
      await client.logout();
    } catch {
      // ignore
    }
  }
}
